/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    kotlin("jvm") version "2.2.0"
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://jogamp.org/deployment/maven/")
        content { includeGroupByRegex("org\\.jogamp(\\..*)?") }
    }
}

// Preserve the upstream gitlink: compile a generated tree with our common overlays.
val overlayPaths = fileTree("src/pvp/java").files.map { it.relativeTo(file("src/pvp/java")).invariantSeparatorsPath }
val preparePvpSources by tasks.registering(Sync::class) {
    from("src/main/java") { exclude(overlayPaths); exclude("**/.git") }
    from("src/pvp/java")
    into(layout.buildDirectory.dir("generated/sources/pvp"))
}

sourceSets {
    main {
        java.setSrcDirs(listOf(layout.buildDirectory.dir("generated/sources/pvp")))
        resources {
            setSrcDirs(listOf("src/main/java", "src/main/resources"))
            exclude("**/*.java", "**/*.kt", "**/.git")
        }
    }
}
// Kotlin and Java both register the default resources; package each path once.
tasks.named<ProcessResources>("processResources") {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.withType<org.gradle.jvm.tasks.Jar> {
    manifest {
        attributes(
            "Main-Class" to "main.MainBCU",
            "Add-Opens" to "java.base/java.lang java.desktop/sun.java2d java.desktop/sun.awt java.desktop/sun.awt.windows"
        )
    }
}

dependencies {
    implementation("org.java-websocket:Java-WebSocket:1.6.0")
    runtimeOnly("org.slf4j:slf4j-simple:2.0.16")
    api(libs.commons.codec.commons.codec)
    api(libs.commons.io.commons.io)
    api(libs.commons.logging.commons.logging)
    api(libs.org.apache.httpcomponents.httpclient)
    api(libs.org.apache.httpcomponents.httpcore)
    api(libs.org.apache.httpcomponents.httpmime)
    api(libs.org.jcodec.jcodec)
    api(libs.org.jcodec.jcodec.javase)
    api(libs.com.google.api.client.google.api.client)
    api(libs.com.google.http.client.google.http.client)
    api(libs.org.json.json)
    api(libs.com.googlecode.soundlibs.tritonus.share)
    api(libs.com.googlecode.soundlibs.vorbisspi)
    api(libs.org.jogamp.jogl.jogl.all)
    api(libs.org.jogamp.gluegen.gluegen.rt)
    api(libs.org.jogamp.jogl.jogl.all.main)
    api(libs.org.jogamp.gluegen.gluegen.rt.main)
    api(libs.com.google.apis.google.api.services.drive)
    api(libs.com.google.oauth.client.google.oauth.client.jetty)
    api(libs.com.google.code.gson.gson)
    api(libs.org.jetbrains.kotlin.kotlin.stdlib.jdk8)
    testImplementation(libs.org.jetbrains.kotlin.kotlin.test)
}

group = "com.battlecatsultimate"
version = "0.0.1-SNAPSHOT"
description = "BCU-java-PC"

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
    options.release = 8
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}

kotlin {
    jvmToolchain(21)
    compilerOptions.jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_1_8)
    sourceSets.named("main") { kotlin.setSrcDirs(listOf(layout.buildDirectory.dir("generated/sources/pvp"))) }
}

tasks.named("compileKotlin") { dependsOn(preparePvpSources) }
tasks.named("compileJava") { dependsOn(preparePvpSources) }
val pvpTests by tasks.registering(JavaExec::class) {
    dependsOn(tasks.named("testClasses"))
    classpath = sourceSets.test.get().runtimeClasspath
    mainClass.set("online.tests.AllTests")
    jvmArgs("-ea", "-Djava.awt.headless=true", "-Dfile.encoding=UTF-8")
}
// The suite deliberately uses a main-based runner (also invoked by Maven),
// not JUnit annotations. Both `test` and `check` must execute it.
tasks.named<Test>("test") {
    dependsOn(pvpTests)
    failOnNoDiscoveredTests.set(false)
}
tasks.named("check") { dependsOn(pvpTests) }
